<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.uiAutomatiom.testScript.Test1" tests="1" time="0.040" ignored="9" failures="0" timestamp="24 Nov 2018 08:05:22 GMT" skipped="0" hostname="UCG-NZWKS-WV08" errors="1">
  <testcase name="testLogin" time="0.040" classname="com.uiAutomatiom.testScript.Test1">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.uiAutomatiom.testScript.Test1.testLogin(Test1.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLogin -->
  <testcase name="beforeTest" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- beforeTest -->
  <testcase name="beforeTest" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- beforeTest -->
  <testcase name="beforeTest" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- beforeTest -->
  <testcase name="afterTest" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- afterTest -->
  <testcase name="afterTest" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- afterTest -->
  <testcase name="afterTest" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- afterTest -->
  <testcase name="beforeSuite" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- beforeSuite -->
  <testcase name="beforeSuite" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- beforeSuite -->
  <testcase name="beforeSuite" classname="com.uiAutomatiom.TestBase.TestBase">
    <skipped/>
  </testcase> <!-- beforeSuite -->
</testsuite> <!-- com.uiAutomatiom.testScript.Test1 -->
